name: "Nested Reusable Workflow"

on:
  workflow_call:

jobs:
  call_reusable_workflow:
    uses: kumabes-org/reusable-workflow/.github/workflows/sample.yaml@release/v1.0.0
    with:
      name: "release/v1.0.0"